# These are supported funding model platforms

praveencs87: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
PraveenCS: # Replace with a single Patreon username
praveen-cs: # Replace with a single Open Collective username
praveencs: # Replace with a single Ko-fi username
praveencs: # Replace with a single Liberapay username
praveencs: # Replace with a single Buy Me a Coffee username
praveencs87: # Replace with a single thanks.dev username
